version: '3'

services:
  db:
    image: postgres:15
    container_name: ${COMPOSE_PROJECT_NAME}-joplinserver_db
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ${DATA_PATH}/data/postgres:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  app:
    image: joplin/server:latest
    container_name: ${COMPOSE_PROJECT_NAME}-joplinserver_app
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
      - db
    ports:
      - "22300:22300"
    restart: always
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=db

      - MAILER_ENABLED=${MAILER_ENABLED}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_SECURE=${MAILER_SECURE}
      - MAILER_AUTH_USER=${MAILER_AUTH_USER}
      - MAILER_AUTH_PASSWORD=${MAILER_AUTH_PASSWORD}
      - MAILER_NOREPLY_NAME=${MAILER_NOREPLY_NAME}
      - MAILER_NOREPLY_EMAIL=${MAILER_NOREPLY_EMAIL}

